USE TATASTEEL1;

CREATE TABLE CUSTOMERS(
CUST_ID INT NOT NULL,
CUST_NAME NVARCHAR(50) NOT NULL,
CUST_ADD NVARCHAR(50) NOT NULL,
CUST_AGE INT NOT NULL
);


INSERT INTO CUSTOMERS(CUST_ID,CUST_NAME,CUST_ADD,CUST_AGE)
	VALUES(1,'SUSANTA KUMAR PANDA','JODA',32);

SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS(CUST_ID,CUST_NAME,CUST_ADD,CUST_AGE)
	VALUES(2,'MADHU CHANDA PALO','BANGALOUR',30);

INSERT INTO CUSTOMERS(CUST_ID,CUST_NAME,CUST_ADD,CUST_AGE)
	VALUES(3,'GAGAN BIHARI PANDA','JAJPUR',60);

ALTER TABLE CUSTOMERS
ADD GENDER VARCHAR(10)


UPDATE CUSTOMERS 
SET GENDER ='F'
WHERE CUST_ID = 2